version: "3"

services:

  database:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: system_track_email

      